_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 3
device:
    value: cpu
early_stopping_patience:
    value: 3
epochs:
    value: 10
learning_rate:
    value: 0.001
loss_function:
    value: None
optimizer:
    value: Adam
